project:
  type: website
  output-dir: docs

website:
  title: "Rowan Green"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - href: outreach.qmd
        text: Outreach

format:
  html:
    theme: lumen
    css: styles.css
    toc: true