---
title: "Outreach"
editor: visual
---

# **Public engagement & outreach**

- Activity facilitator at ‘Meeting the Microbes’ BRC outreach event at Vancouver Science World (2025)

- Coproduction of a press release on (Green et al, 2024, PLOS biology) for the [Manchester University news site](https://www.manchester.ac.uk/about/news/scientists-control-bacterial-mutations-to-preserve-antibiotic-effectiveness/). This was picked up by multiple news and popular science sites including: msn.com, phys.org, ddw-online.com, drugscontrol.org, psychreg.org, azolifesciences.com and myscience.org

- Activity facilitator at [Manchester Community Festival](https://universallymanchester.com/) ‘You & Your Microbes’ (2022-2024)

- [The Brilliant Club](https://thebrilliantclub.org/) – Delivery of university style group tutorials to students aged 12-13 from backgrounds underrepresented in higher education (2021-2024)

- Delivery of hands-on primary school workshops on enzyme action and the cells that make our bodies for Science Week (2023)

- Public talk for ‘[Pint of Science](https://pintofscience.co.uk/)’ festival: ‘Antibiotic Resistance: The Deadly Power of Evolution’ (2022)
